version: '3.1'

services:

    wordpress:
        image: wordpress:php5.6-apache
        environment:
            WORDPRESS_DB_HOST: mysql
            WORDPRESS_DB_USER: root
            WORDPRESS_DB_PASSWORD: 1234
            WORDPRESS_DB_NAME: wordpress
        volumes:
            - ./:/var/www/html/wp-content/plugins/landingi-landing-pages/
        labels:
            - "traefik.enable=true"
            - "traefik.port=80"
            - "traefik.default.protocol=http"
            - "traefik.frontend.rule=Host:wordpress.landingi.it"
            - "traefik.backend=wordpress"
            - "traefik.docker.network=devkit_landingi"
        networks:
            landingi:
                aliases:
                    - wordpress.landingi.it

networks:
    landingi:
        external:
            name: devkit_landingi
